enable_analysis: true

learning_rate: 1e-6
output_dir: saliency_map/logs

dataset_name: lmms-lab/Math10K
model_name_or_path: openlm-research/open_llama_3b # Qwen/Qwen2.5-1.5B #NousResearch/Llama-2-7b-hf
trust_remote_code: true
use_cpu: false
attn_implementation: flash_attention_2
seed: 42
torch_dtype: bfloat16

